// Fixed consignes corpus for exerciseType "commentaire" — Gabriel, 2026-09-24.
// Grounded in the official EAF barème (reproduced verbatim from the
// consigne.md Gabriel wrote by hand for TP 1SCHA Sujet A) plus the
// methodological findings from reviewing Groupes 2-8 of that same TP:
// - how to read a plan in a rédaction that never carries axis/sous-partie
//   headers (titles live in the intro, after the problématique; a
//   sous-partie's argument lives in its first or second sentence);
// - the complétude/équilibre check, kept separate from interpretive depth,
//   so a rushed axis (visible, often self-reported by the élève) isn't
//   conflated with a poorly-argued one;
// - the paraphrase-vs-thèse test for Contenu, and the contresens/citation-
//   fidelity/terminology checks that surfaced repeatedly across Groupes 3-8;
// - the group-copy note on Expression (variable graphie/register across
//   paragraphs is a neutral observation, not an individual fault).
// This text is identical for every évaluation of this type; only the
// "Paramètres de cette évaluation" block and the compléments are per-évaluation
// (see ConsignesBuilder.js).

.pragma library

function fixedBlock() {
  return [
"# Nature de l'exercice",
"",
"Il s'agit d'un commentaire de texte, rédigé intégralement (introduction, développement organisé en",
"deux ou trois axes eux-mêmes divisés en deux ou trois sous-parties, conclusion).",
"",
"# Barème officiel de l'épreuve anticipée de français (EAF) — commentaire",
"",
"## Aptitude à comprendre, à analyser et à interpréter un texte littéraire",
"",
"### Aptitude à comprendre un texte littéraire",
"- Palier 1 : Le candidat n'a pas saisi le sens du texte.",
"- Palier 2 : Le candidat a très partiellement saisi le sens du texte.",
"- Palier 3 : Le candidat a saisi l'essentiel du sens du texte malgré quelques confusions.",
"- Palier 4 : Le candidat a saisi le sens du texte.",
"",
"### Aptitude à analyser et à interpréter un texte littéraire",
"- Palier 1 : Le candidat ne propose pas d'analyse du texte.",
"- Palier 2 : Le candidat entreprend d'analyser le texte et/ou en propose une interprétation superficielle",
"  ou peu pertinente.",
"- Palier 3 : Le candidat analyse le texte et en propose une interprétation souvent pertinente.",
"- Palier 4 : Le candidat construit un discours interprétatif de qualité.",
"",
"## Aptitude à mobiliser une culture littéraire fondée sur les travaux conduits en cours de français,",
"sur des connaissances et des lectures personnelles",
"- Palier 1 : Le candidat ne convoque pas d'éléments de connaissance littéraire lui permettant de situer",
"  ou de comprendre le texte.",
"- Palier 2 : Le candidat convoque quelques éléments de connaissance littéraire, mais avec maladresse",
"  et/ou peu de pertinence.",
"- Palier 3 : Le candidat convoque quelques éléments de connaissance littéraire pertinents pour enrichir",
"  sa compréhension et/ou son interprétation du texte.",
"- Palier 4 : Le candidat s'appuie sur ses connaissances littéraires pour faire émerger la singularité du",
"  texte et l'interpréter.",
"",
"## Aptitude à construire une réflexion en prenant appui sur un texte et à la rendre intelligible",
"- Palier 1 : Le propos n'est pas organisé.",
"- Palier 2 : Le propos est organisé de manière peu pertinente.",
"- Palier 3 : Le propos est organisé de manière globalement cohérente.",
"- Palier 4 : Le propos est organisé de manière cohérente. Il suit un fil conducteur perceptible et",
"  pertinent.",
"",
"## Maîtrise de la langue et de l'expression à l'écrit",
"",
"### Aptitude à respecter les normes orthographiques et syntaxiques",
"- Palier 1 : Le texte ne respecte pas les normes orthographiques et syntaxiques.",
"- Palier 2 : Le texte respecte trop peu les normes orthographiques et syntaxiques.",
"- Palier 3 : Le texte respecte globalement les normes orthographiques et syntaxiques.",
"- Palier 4 : Le texte respecte les normes orthographiques et syntaxiques. Il peut comporter quelques",
"  étourderies graphiques.",
"",
"### Aptitude à utiliser une langue correcte et adaptée",
"- Palier 1 : Le texte est écrit dans une langue incorrecte et/ou révèle un niveau de langue inadapté.",
"- Palier 2 : Le texte est écrit dans une langue parfois incorrecte et/ou inadaptée.",
"- Palier 3 : Le texte est écrit dans une langue globalement correcte et adaptée.",
"- Palier 4 : Le texte est écrit dans une langue riche et soignée.",
"",
"## Points par palier à pondérer",
"- Palier 1 : 1 à 6 pts",
"- Palier 2 : 7 à 11 pts",
"- Palier 3 : 12 à 17 pts",
"- Palier 4 : 18 à 20 pts",
"",
"## Explicitation des compétences du barème",
"",
"### Aptitude à comprendre, à analyser et à interpréter un texte littéraire",
"On évalue la capacité du candidat à :",
"- Rendre compte du sens du texte ;",
"- Percevoir le mouvement/la composition du texte ;",
"- Identifier et analyser des éléments saillants du texte ;",
"- Percevoir et exploiter les implicites et les résistances du texte ;",
"- Proposer une réception sensible du texte ;",
"- Interroger la portée (morale, esthétique, historique) du texte.",
"",
"### Aptitude à mobiliser une culture littéraire",
"On évalue la capacité du candidat à :",
"- Convoquer des références culturelles pour, au besoin, enrichir sa compréhension et son interprétation",
"  du texte ;",
"- S'appuyer sur sa culture littéraire et artistique pour faire émerger la singularité du texte (par",
"  comparaison ou différenciation).",
"",
"### Aptitude à construire une réflexion en prenant appui sur un texte et à la rendre intelligible",
"On évalue la capacité du candidat à :",
"- Rendre compte de sa lecture de manière organisée ;",
"- Étayer clairement son cheminement dans le texte ;",
"- Mettre en lien, hiérarchiser et catégoriser ses remarques.",
"",
"### Maîtrise de la langue et de l'expression à l'écrit",
"On évalue la capacité du candidat à :",
"- Veiller à la cohérence textuelle de son écrit ;",
"- Utiliser une langue correcte et adaptée (lexique, niveau de langue) ;",
"- Respecter globalement les normes orthographiques et syntaxiques.",
"",
"# Méthode — comment lire un commentaire rédigé (ne pas chercher de titres)",
"",
"Un commentaire composé rédigé ne comporte JAMAIS de titre d'axe ni de titre de sous-partie inscrit",
"comme tel dans la copie — ce n'est pas un plan détaillé sous forme de liste. La structure s'y lit",
"autrement, et tu dois la chercher aux bons endroits avant de conclure qu'elle est absente :",
"",
"- Le(s) titre(s) d'axe(s) sont normalement formulés dans l'introduction, juste après la problématique,",
"  au moment de l'annonce de plan (« nous verrons que... », « il s'agira d'abord de... »).",
"- Une phrase d'ouverture facultative peut annoncer un axe juste avant son premier paragraphe, mais son",
"  absence n'est pas une faute.",
"- L'argument de chaque sous-partie se trouve le plus souvent dans la PREMIÈRE phrase de son paragraphe,",
"  ou dans la deuxième si la première n'est qu'une transition ou un connecteur isolé (« Tout d'abord, »,",
"  « Ensuite, »...). C'est cette phrase qu'il faut lire pour restituer l'argument, pas une liste à puces",
"  qui n'existera jamais dans une copie rédigée.",
"",
"## Étape à mener AVANT toute lecture interprétative : restituer et évaluer le plan",
"",
"Avant de juger le fond, essaie de restituer, uniquement à partir de ces indices, le plan détaillé de la",
"copie : problématique, titre de chaque axe, argument de chaque sous-partie, présence ou non de phrases de",
"transition/synthèse. Pour chaque élément, distingue explicitement trois cas, à consigner dans le log :",
"- **trouvé** : l'élément est formulé clairement, tu le rapportes tel quel ;",
"- **reconstruit** : l'élément n'est pas formulé clairement, tu as dû l'inférer du contenu — signale-le",
"  comme tel, car c'est le signe d'une faiblesse de méthode chez l'élève, pas une invitation à lire à sa",
"  place ;",
"- **absent** : aucun élément ne permet de le restituer, même en reconstruisant.",
"",
"Une fois le plan restitué, évalue-le sur deux points distincts, à ne pas confondre :",
"1. **Complétude** : le nombre de sous-parties par axe correspond-il à ce qui est attendu pour l'exercice",
"   (deux ou trois) ? Un axe qui n'en compte qu'une, ou une conclusion sans réponse à la problématique, est",
"   un plan incomplet.",
"2. **Équilibre** : les sous-parties et les axes sont-ils développés de façon comparable (longueur, nombre",
"   de citations, présence d'un procédé nommé) ? Un axe nettement plus court ou plus pauvre que les autres,",
"   a fortiori si la copie se termine par une mention explicite du type « manque de temps », signale un",
"   problème de gestion du temps de l'épreuve — à nommer comme tel dans l'appréciation, et à distinguer",
"   clairement d'une faiblesse de raisonnement. Les deux diagnostics appellent un conseil différent : gérer",
"   son temps n'est pas la même chose que mieux argumenter.",
"",
"# Contenu — au-delà du simple repérage de procédés",
"",
"Pour chaque procédé littéraire relevé par l'élève, vérifie si la phrase qui suit se contente de",
"reformuler la citation (paraphrase) ou si elle articule explicitement un lien de cause à effet vers la",
"thèse de l'axe / la réponse à la problématique. Une identification correcte d'un procédé sans ce second",
"geste reste un repérage, pas une interprétation aboutie — signale la différence sans la confondre avec",
"une erreur.",
"",
"Distingue toujours deux natures d'erreur bien différentes :",
"- une interprétation **insuffisamment développée** (le lien à la thèse n'est pas fait, mais rien de ce",
"  qui est écrit n'est faux) ;",
"- un **contresens**, c'est-à-dire une inversion ou une erreur de compréhension du sens même du texte",
"  (ex. attribuer à la raison ce que le texte attribue à la passion, ou inversement). Un contresens est",
"  une erreur de fond plus grave qu'un manque de profondeur, et doit être signalé sans ambiguïté comme",
"  tel, avec la citation exacte du texte source à l'appui pour que l'erreur soit vérifiable.",
"",
"Vérifie systématiquement la fidélité des citations données par l'élève par rapport au texte du sujet",
"(pas seulement leur pertinence) : un mot changé peut suffire à inverser le sens de la citation (ex.",
"« veux-je » déformé en « vais-je »). Si tu identifies un écart, signale-le avec la citation exacte du",
"texte source.",
"",
"Vérifie également la justesse de la terminologie employée pour nommer un procédé (une hyperbole n'est",
"pas un pléonasme, un superlatif n'est pas nécessairement une hyperbole) — sans devenir pointilleux sur",
"des cas réellement limites ou défendables.",
"",
"# Expression — cas particulier du travail de groupe",
"",
"Si la copie est un travail de groupe (plusieurs rédacteurs), il est normal et attendu que la qualité de",
"la graphie et de l'expression varie d'un paragraphe à l'autre. Signale toute variation notable — y",
"compris l'orthographe instable d'un nom propre central au texte (ex. le nom de l'héroïne épelé",
"différemment selon les paragraphes) — comme une observation neutre destinée à l'enseignant, sans en",
"faire porter la responsabilité individuellement sur l'élève dont tu ne connais pas l'identité."
  ].join("\n")
}
